### ISSUE TITLE
Python3 not found

### ISSUE THREAD

**Issue by bouff** [cibuilds/snapcraft#36]
We've been using `cibuilds/snapcraft:core18` without any issues for some time now.

In the latest image (pushed: Dec 13, 2021 at 5:14am), we are unable to build due the following error:
```
/snap/bin/snapcraft: 13: exec: /snap/snapcraft/current/usr/bin/python3: not found

Exited with code exit status 127
CircleCI received exit code 127
```

Looking in the container during a build, everything appears ok (at-a-glance):
```
$ cat /snap/bin/snapcraft
#!/bin/sh

SNAP="/snap/snapcraft/current"
SNAP_NAME="$(awk '/^name:/{print $2}' $SNAP/meta/snap.yaml)"
SNAP_VERSION="$(awk '/^version:/{print $2}' $SNAP/meta/snap.yaml)"
SNAP_ARCH="amd64"

export SNAP
export SNAP_NAME
export SNAP_VERSION
export SNAP_ARCH

exec "$SNAP/usr/bin/python3" "$SNAP/bin/snapcraft" "$@"
$
$ /snap/snapcraft/current/usr/bin/python3
-bash: /snap/snapcraft/current/usr/bin/python3: No such file or directory
$
$ ls -lart /snap/snapcraft/current/usr/bin/python3
lrwxrwxrwx 1 root root 9 Mar 13  2020 /snap/snapcraft/current/usr/bin/python3 -> python3.8
$
$ ls -lart /snap/snapcraft/current/usr/bin/python3.8
-rwxr-xr-x 1 root root 5494584 Oct 27 01:22 /snap/snapcraft/current/usr/bin/python3.8
```

**Comment by snowsky** [comment]
A workaround here, https://forum.snapcraft.io/t/snapcraft-failed-in-container/27921/3 :)

**Comment by krille-chan** [comment]
Any news on this? I use this docker image in the gitlab CI and this bug breaks all of my builds

**Comment by mardy** [comment]
@krillefear I'm now using the `ubuntudesktop/gnome-3-38-2004` images, which I found mentioned in Remmina's gitlab-ci file: https://gitlab.com/Remmina/Remmina/-/blob/master/.gitlab-ci.yml

**Comment by FelicianoTech** [comment]
This image is now deprecated. There's a note at the top of the readme.
