### ISSUE TITLE
Completely Overhaul the CircleCI Snapcraft Doc

### ISSUE THREAD

**Issue by felicianotech** [cibuilds/snapcraft#8]
Once #7 is closed, the CircleCI Snapcraft Doc needs to be rewritten.

The doc: https://circleci.com/docs/2.0/build-publish-snap-packages/
A closed PR that should be consulted before rewritting: https://github.com/circleci/circleci-docs/pull/3441

**Comment by FelicianoTech** [comment]
This image is now deprecated. There's a note at the top of the readme.
